name: CI

on:
  push:
    branches: [ main trackVote-api tracks-api ]
  pull_request:
    branches: [ main trackVote-api tracks-api ]
    
jobs:
  build:
    name: Build-linux
    runs-on: ubuntu-latest
#   build1:
#     name: Build-Windows
#     runs-on: windows-latest
#   build2:
#     name: Build-Mac
#     runs-on: macos-latest
  
    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Restore node_modules from cache
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm ci && npm run build --if-present
  # Deploying running on herouk
